Add some methods to Priority Queue
google/ac-library.cr pull request #10
Opened 2023-01-28 16:58 UTC by ngng628

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

## Changes
- Add `#peek` / `#peek?`
- Add `.min` (Min Heap)
- Add `.max` (Max Heap)
- Add description to `README.md`

2023-01-28 19:35 UTC, ngng628 commented
I have added `PriorityQueue(T).new(elems)`.

This change slightly improves performance.

```cr
PriorityQueue(Int32).new([3, 1, 4, 1, 5])
PriorityQueue(Int32).min([3, 1, 4, 1, 5])
PriorityQueue(Int32).max([3, 1, 4, 1, 5])
```

2023-01-28 20:21 UTC, hakatashi requested changes
### レビューのラベルについて

`[MUST]` 明確なバグやセキュリティリスクなど、必ず修正されるべき内容であることを表します。
`[SHOULD]` 読みにくいコードや技術負債になるコードなど、修正されるべき内容であることを表します。SHOULD以上のコメントが1つでもある場合は基本的にLGTMは出しません。
`[MAY]` コーディングのベストプラクティスなど、最悪修正しなくてもいいが原則として修正してほしい内容であることを表します。
`[nit]` not important though の略です。修正してもしなくてもいい内容であることを表します。

`[QUESTION]` 修正提案ではなく、コードの不明点などに対する質問です。MUSTやSHOULDのコメントと同じく、質問が解決されない場合はLGTMできない内容であることが多いです。
`[info]` 単なる提案やメモなど、修正を伴わないコメントを表します。

2023-01-28 20:21 UTC, hakatashi commented on src/priority_queue.cr
> +    def peek
[SHOULD] このメソッドはクラスに対してイミュータブルなので、名前は動詞ではなく名詞が望ましいと思います。

他の言語の Priority Queue だと `top` や `head` などの名前で呼ばれているようですが、今回はCrystalのEnumerableなどの例にならって `first` が適しているように思います。

(ちなみに、将来的にPriorityQueueがEnumerableを実装するようにしてもいいかもしれません)

2023-01-28 20:21 UTC, hakatashi commented on src/priority_queue.cr
> +    def initialize(elems : Indexable(T), &block : T, T -> Bool)
[SHOULD] ドキュメントを追加してください

2023-01-29 04:19 UTC, ngng628 commented on src/priority_queue.cr
> +    def peek
`#peek` は削除しました。

代わりに、`PriorityQueue` を `Enumerable` に変更しました。

ただし、ヒープを壊さず効率的に `#each` を定義する方法がおそらくないため、`#each` は `@heap.sort.each` に対応させ、`first` のみを最適化しました。

（ちなみに、要素をすべて列挙するならこの方法が効率的ですが、そうでないならPriorityQueueをディープコピーしたあとpopしたほうが高速でした。ライブラリには組み込んでいません。）

2023-01-29 04:22 UTC, ngng628 commented on src/priority_queue.cr
> +    def initialize(elems : Indexable(T), &block : T, T -> Bool)
適宜ドキュメントを追加しました。`README.md` に `#each` の計算量に関する記述も追加しました。

2023-02-01 02:03 UTC, hakatashi approved these changes
よさそうです ありがとうございます!

2023-02-01 02:03 UTC, merged