Improve PriorityQueue
google/ac-library.cr pull request #22
Opened 2023-09-03 08:39 UTC by ngng628

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

## Overview
- 標準ライブラリに合わせて `#push` と `#<<` が `self` を返すように変更
- `nil` を返さない `pop!` を追加

2023-09-05 10:54 UTC, hakatashi requested changes
変更内容は良さそうです!

* ユニットテストを追加してください
* masterのほうをいじったのでrebaseかmergeお願いします

2023-09-06 02:14 UTC, ngng628 commented
> 変更内容は良さそうです!
> 
> * ユニットテストを追加してください
> * masterのほうをいじったのでrebaseかmergeお願いします

追加しました！

2023-09-06 02:15 UTC, ngng628 commented
> 変更内容は良さそうです!
> 
> * ユニットテストを追加してください
> * masterのほうをいじったのでrebaseかmergeお願いします

追加しました！

2023-09-07 01:38 UTC, hakatashi approved these changes
ありがとうございます!

2023-09-07 01:38 UTC, merged