Add support for the `FenwickTree#sum` with open ended ranges
google/ac-library.cr pull request #23
Opened 2023-09-03 17:54 UTC by ngng628

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

## Overview

- 標準ライブラリに合わせて `range` で open ended ranges に対応させました。
   - `tree[..3]`
   -  tree[1..]`
   - `tree[...]`

2023-09-05 10:58 UTC, hakatashi requested changes

2023-09-05 10:58 UTC, hakatashi commented on spec/fenwick_tree_spec.cr
> +      tree[...11].should eq 55
[SHOULD] 境界値が分かりづらいので、全部ではなく途中からの値を取ってくるテストを追加してください ([...5]など)

[SHOULD] inclusiveかつstart側がopen-endedなテストを追加してください

2023-09-06 02:00 UTC, ngng628 commented on spec/fenwick_tree_spec.cr
> +      tree[...11].should eq 55
追加しました！確認お願いします。

2023-09-07 01:39 UTC, hakatashi approved these changes
ありがとうございます!

2023-09-07 01:39 UTC, merged