Add support for the `SegTree#sum` and `LazySegTree#sum` with open ended ranges
google/ac-library.cr pull request #24
Opened 2023-09-03 18:10 UTC by ngng628

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

## Overview
- 標準ライブラリに合わせて `Range` で open ended ranges に対応させました。
   - `tree[..3]`
   - `tree[1..]`
   - `tree[...]`

2023-09-05 11:03 UTC, hakatashi requested changes
変更内容は良さそうです!

* ユニットテストを追加してください
* masterのほうをいじったのでrebaseかmergeをお願いします

2023-09-06 02:00 UTC, ngng628 commented
> 変更内容は良さそうです!
> 
> * ユニットテストを追加してください
> * masterのほうをいじったのでrebaseかmergeをお願いします

追加しました！確認お願いします。

2023-09-06 02:35 UTC, ngng628 commented
> 変更内容は良さそうです!
> 
> * ユニットテストを追加してください
> * masterのほうをいじったのでrebaseかmergeをお願いします

追加しました！

2023-09-07 01:41 UTC, hakatashi approved these changes
ありがとうございます!

2023-09-07 01:41 UTC, merged