Port Z-Algorithm
google/ac-library.cr pull request #8
Opened 2023-01-28 03:55 UTC by ngng628

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

## Original

- [ac-library/string.hpp at z_algorithm](https://github.com/atcoder/ac-library/blob/f669803f78c3acc72671ca6e41b4eeb0469364a8/atcoder/string.hpp#L245-L271)

2023-01-28 20:35 UTC, hakatashi requested changes

2023-01-28 20:35 UTC, hakatashi commented on spec/String_spec.cr
> +require "../src/string.cr"
[MUST] Google下で公開されるソースコードファイルには、必ず Apache License と著作権者を示すヘッダーが必要です。

詳しくは、Googleのオープンソースドキュメントの [Include LICENSE file and source code headers](https://opensource.google/documentation/reference/releasing/preparing#license-headers) を参照してください。

著作権者名には、あなたの名前か、"Google LLC" を使用してください (後者の場合、Googleが作成したコードにあなたがパッチを行ったという扱いになります)。

2023-01-29 04:29 UTC, ngng628 commented on spec/String_spec.cr
> +require "../src/string.cr"
確認不足でした。ご指摘ありがとうございます。

他のソースコードファイルと同様のライセンス表記を追加しました。

このプルリクエストとは別件ですが、`src/atcoder.cr`  (https://github.com/google/ac-library.cr/blob/master/src/atcoder.cr) にもヘッダーを記載していないため変更したほうが良さそうですね。

2023-02-01 02:02 UTC, hakatashi commented on spec/String_spec.cr
> +require "../src/string.cr"
あっ本当ですね、直しておきます。ありがとうございます。

2023-02-01 02:03 UTC, hakatashi approved these changes
よさそうです ありがとうございます!

2023-02-01 02:03 UTC, merged